services:
  backend:
    build:
      context: ./backend/level-up
    container_name: levelup-backend
    ports:
      - "5001:3000"
    volumes:
      - ./backend/level-up:/usr/src/app
    env_file:
      - ./backend/level-up/.env
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend/level-up
    container_name: levelup-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


  postgres:
    image: postgres:15
    container_name: levelup-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: levelup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
